### ISSUE TITLE
Allow callback to return false to stop traversal

### ISSUE THREAD

**Issue by TimothyBJacobs** [epoberezkin/json-schema-traverse#2]
When traversing a schema to find whether a keyword is defined or not, it is helpful to be able to stop the traversal once a keyword is found.

Happy to submit a patch if this is ok with you.

**Comment by epoberezkin** [comment]
The standard pattern for functions that iterate arrays is to throw exception in order to stop iteration - it can be used here as well. Some special error can be used to differentiate from other exceptions.

Checking (and passing up) callback return value would complicate code, so I'd rather not add it.

**Comment by TimothyBJacobs** [comment]
Understood, that makes sense. Thanks for considering it.
